# -*- mode: ruby -*-
# vi: set ft=ruby :
$script = <<SCRIPT

echo Installing dependencies...
sudo apt-get install -y unzip

echo Fetching Consul...
cd /tmp/
wget https://dl.bintray.com/mitchellh/consul/0.3.0_linux_amd64.zip -O consul.zip

echo Installing Consul...
unzip consul.zip
sudo chmod +x consul
sudo mv consul /usr/bin/consul

SCRIPT

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

  config.vm.provision "shell", inline: $script

  config.vm.provider :virtualbox do |p|
     p.customize ['modifyvm', :id, '--memory', '1024', '--ioapic', 'on']
  end

  config.vm.define "n1" do |n|
      n.vm.hostname = "n1"
      n.vm.network "private_network", ip: "172.20.21.10"
  end

  config.vm.define "n2" do |n|
      n.vm.hostname = "n2"
      n.vm.network "private_network", ip: "172.20.21.11"
  end

  config.vm.define "n3" do |n|
      n.vm.hostname = "n3"
      n.vm.network "private_network", ip: "172.20.21.12"
  end

end
