# -*- mode: ruby -*-
# vi: set ft=ruby :
# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

  #config.vm.provision "shell", inline: $script

  config.vm.provider :virtualbox do |p|
     p.customize ['modifyvm', :id, '--memory', '1024', '--ioapic', 'on']
  end

  config.vm.define "ubuntu-01" do |n|
      n.vm.hostname = "ubuntu-01"
      n.vm.network "private_network", ip: "172.20.21.10"
  end

  config.vm.define "ubuntu-02" do |n|
      n.vm.hostname = "ubuntu-02"
      n.vm.network "private_network", ip: "172.20.21.11"
  end

  config.vm.define "ubuntu-03" do |n|
      n.vm.hostname = "ubuntu-03"
      n.vm.network "private_network", ip: "172.20.21.12"
  end

  config.vm.define "ubuntu-04" do |n|
      n.vm.hostname = "ubuntu-04"
      n.vm.network "private_network", ip: "172.20.21.13"
  end

end
